### PR TITLE
[Tests] Fix unit tests failing on windows and improve OBJFile

### PR DESCRIPTION
**Pull request by HannesWell**
The following unit-tests failed on my windows-computer:
- TestObjFile: The URL was not properly constructed to work on windows
- TestCamera_EmulGL_Onscreen: frame-borders were not considered
- TestCameraNative_Viewport: frame-borders were not considered as well as the minimum-frame size on windows

This PR fixes them (at least on my windows computer).

Besides that I applied some minor improvements to OBJFile.java which I noticed while fixing the mentioned unit-tests

### CODE REVIEW

**Comment by HannesWell** [comment]
Furthermore the tests in the java9/High-DPI also fail on my windows computer which does not have a High-DPI Display.
The failures are either due to image size difference or pixel difference. Is it possible that not having a High-DPI display causes these failures respectively can the tests be GPU depended like the integration tests?

If yes I suggest to only execute these tests in the `integration-tests` profile as well and offer to add another commit to this PR.

**Comment by jzy3d** [comment]
I apologize forgetting this. I think I also did the same changes on my side. I keep this "in progress" to ensure I implemented everything you implemented.

I confirm the tests in java9 module are GPU dependent. They are intended to be ran with `-Pintegration-tests`.

For these ITTests, I am thinking of adding a file indicating which computer generated the baseline to ensure that only a computer with the same OS/GPU/JDK will verify them.

**Comment by jzy3d** [comment]
Hi @HannesWell ,

Same issue for me trying to merge from CLI : 

```
martin@OCTO-MPE:jzy3d-api (master $) $ git checkout -b HannesWell-unitTests master
Basculement sur la nouvelle branche 'HannesWell-unitTests'
martin@OCTO-MPE:jzy3d-api (HannesWell-unitTests $) $ git pull git://github.com/HannesWell/jzy3d-api.git unitTests
fatal: impossible de se connecter à github.com :
github.com[0: 140.82.121.3]: errno=Operation timed out
```

Most of the fix you proposed have been applied in the meantime (I also work on Windows sometime!), but not the one about EmulGL viewport, which I simply copy pasted from you and added in a dedicated branch [here](https://github.com/jzy3d/jzy3d-api/pull/272).

As for the other issue, I close but you can consider you work merged.

Thank you again!

**Comment by jzy3d** [comment]
It [surprisingly failed on Ubuntu when ran from CLI](https://github.com/jzy3d/jzy3d-api/runs/6571804795?check_suite_focus=true). Running for IDE is OK, even when using the same JDK that used from CLI. 

I [ignored the test for Linux only](https://github.com/jzy3d/jzy3d-api/commit/7a94b74da9a6c442a52f65f776d9c2ff5ae4ca47) so that it can continue running on Windows and macOS.

**Comment by HannesWell** [comment]
> As for the other issue, I close but you can consider you work merged.
> 
> Thank you again!

Great. Thank you. 

> It [surprisingly failed on Ubuntu when ran from CLI](https://github.com/jzy3d/jzy3d-api/runs/6571804795?check_suite_focus=true). Running for IDE is OK, even when using the same JDK that used from CLI.
> 
> I [ignored the test for Linux only](https://github.com/jzy3d/jzy3d-api/commit/7a94b74da9a6c442a52f65f776d9c2ff5ae4ca47) so that it can continue running on Windows and macOS.

That's bad but I have no idea why.

But I want to mention that Junit offers `org.junit.Assume` to allow conditional execution of tests.

**Comment by jzy3d** [comment]
Thanks for mentioning Assume. The reasons of the failure are not clear to me yet.

To learn more about unstable tests, you can read this issue : https://github.com/jzy3d/jzy3d-api/issues/269

**Pull request closed without merging**
