### PR TITLE
Swt newt

### PR DESCRIPTION
**Pull request by jacobfilik**
Implementation of charts and factories using swt newt instead of the swt awt bridge.

I've tried to follow similar patterns to the awt classes (except the parent composite is required to construct the swt chart, so needs to passed through the component factory).

Not sure its perfect (still seems to be some awt threads, need to investigate a little further), but certainly works.

Added demos for the bridge and non bridge swt, which both seem to run fine.

Tested in eclipse with OSGI against maven built jzy3d jars packaged in plugin and jogl OSGI bundle.

Happy to get feedback and modify before the request is accepted.

### CODE REVIEW

**Comment by jzy3d** [comment]
You really wrote it how it should be written! Many thanks for your contribution.

I unfortunately crash at runtime with the following error. There are view discussions on the web on the topic, I'll come back later on this problem.

I am eager to run your code!

Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-gtk-4332 in java.library.path
	no swt-gtk in java.library.path
	Can't load library: /Users/martin/.swt/lib/macosx/x86_64/libswt-gtk-4332.jnilib
	Can't load library: /Users/martin/.swt/lib/macosx/x86_64/libswt-gtk.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
	at org.jzy3d.analysis.SWTDemo.main(SWTDemo.java:44)

**Comment by jacobfilik** [comment]
Hmm, I didn't need to change any of the dependencies on my system.

I should be running a pretty vanilla checkout, although I am developing in eclipse, so who knows if it is doing some swt dependency magic under the hood.

I have my work windows machine at home so I will try a clean checkout on that and see if I can reproduce.

How many contributions before I can claim a free developer guide (if that is still offered)? I would really like waterfall plots (http://cloud.originlab.com/images/WikiWeb/Graphing/WaterfallWithHighlightSeries.png?v=3594) and am happy to try and add this myself if it is not already there.

**Comment by jzy3d** [comment]
Yes the developer guide is still offered for new features.

A short doc explaining how to deal with those native dependencies might make the feature complete ;) 

Please send me your email (martin at jzy3d dot org)

**Comment by jzy3d** [comment]
The SWT project was only declaring Linux SWT dependencies but not MacOs.

I added Macos to pom file, but we are not finished yet : classpath search fall on the first definition hence missing macos jars. I don't know how jogl and eclipse deal with jar selection according to OS but it could be inspiring.

Anyway, your example is working perfectly and is very efficient, so congratulation and thanks again :)

https://github.com/jzy3d/jzy3d-api/commit/a247b7811953b67bfd41e8c33be14b0098b3ac35

**Pull request merged**
